a = input ("Qual é o primeiro produto?")
qa = int (input ("Qual é a quantidade do primeiro produto?"))
va = int (input ("Qual é o valor do primeiro produto?"))
b = input ("Qual é o segundo produto?")
qb = int (input ("Qual é a quantidade do segundo produto?"))
vb = int (input ("Qual é o valor do segundo produto?"))
c = input ("Qual é o terceiro produto?")
qc = int (input ("Qual é a quantidade do terceiro produto?"))
vc = int (input ("Qual é o valor do terceiro produto?"))
total = (qa*va)+(qb*vb)+(qc*vc)
print (f'Os produtos"{a}","{b}"e"{c}" tem a quantidade, respetivamente,de"{qa}","{qb}"e"{qc}", e o seu valor total será "{total}".')